version: '3'
services:
  app:
    container_name: ecommerce_app_test
    build:
      dockerfile: ./Dockerfile.test
      context: .
    restart: on-failure
    volumes:
      - .:/ecommerce_app_test
