version: "3"

services:
  ecommerce-service:
    container_name: ecommerce_app
    build: .
    command: go run main.go
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/ecommerce_app
    depends_on:
      - discount-service
    networks:
      - ecommerce-network

  discount-service:
    image: hashorg/hash-mock-discount-service
    container_name: discount_app
    ports:
    - 50051:50051
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce-network
